services:
  # BILLING APPLICATION SERVICE
  billing-app:
    build: .                          # Build image using ./Dockerfile
    ports:
      - "${BILLING_PORT}:5000"                   # Devops asked for 8083
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - BILLING_PORT=${BILLING_PORT}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - WEIGHT_BASE_URL=${WEIGHT_BASE_URL}
    depends_on:
      billing-db:
        condition: service_healthy
    volumes:
      - ./in:/app/in

  # DATABASE SERVICE
  billing-db:
    build: ./db                        # Build image using ./db/Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=billdb
    volumes:
      - billing-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  billing-db-data:
